### ISSUE TITLE
Exception not caught when trying to run with incorrect values in config file

### ISSUE THREAD

**Issue by ShyPixie** [ShyPixie/steam-tools-ng#7]
```
2018-09-27 21:42:26,229 ERROR: Task exception was never retrieved
future: <Task finished coro=<Application.async_activate() done, defined at .\src\gtk\application.py:77> exception=ValueError("invalid literal for int() with base 10: '3545353ggg7777'")>
Traceback (most recent call last):
  File ".\src\gtk\application.py", line 90, in async_activate
  File ".\src\config.py", line 180, in getint
  File ".\src\config.py", line 171, in _get
  File "E:\msys2_64\mingw64\lib\python3.7\configparser.py", line 818, in getint
    fallback=fallback, **kwargs)
  File "E:\msys2_64\mingw64\lib\python3.7\configparser.py", line 808, in _get_conv
    **kwargs)
  File "E:\msys2_64\mingw64\lib\python3.7\configparser.py", line 802, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: '3545353ggg7777'
2018-09-27 21:42:39,984 INFO: Exiting...

```

**Comment by ShyPixie** [comment]
fixed by b5a40a28c89e09a8a3bc517ffa028c831227488c
